<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\TransactionsUpdatesController;
use FortisAPILib\Exceptions;

class TransactionsUpdatesControllerTest extends BaseTestController
{
    /**
     * @var TransactionsUpdatesController TransactionsUpdatesController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getTransactionsUpdatesController();
    }

    public function testVoid()
    {
        // Parameters for the API call
        $transactionId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->void($transactionId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Transaction","data":{"additional_amounts":[{"type":"cashback","amount' .
                '":10,"account_type":"credit","currency":840}],"billing_address":{"city":"Novi",' .
                '"state":"Michigan","postal_code":"48375","phone":"3339998822","country":"USA"},' .
                '"checkin_date":"2021-12-01","checkout_date":"2021-12-01","clerk_number":"AE1234' .
                '","contact_id":"11e95f8ec39de8fbdb0a4f1a","custom_data":{},"customer_id":"custo' .
                'merid","description":"some description","iias_ind":1,"image_front":"U29tZVN0cml' .
                'uZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU' .
                '5vdEJhc2U2NEVuY29kZWQ=","installment":true,"installment_number":1,"installment_' .
                'count":1,"recurring_flag":"yes","installment_counter":1,"installment_total":1,"' .
                'subscription":false,"standing_order":false,"location_api_id":"location-api-id-f' .
                'lorida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show":false,"notification_e' .
                'mail_address":"johnsmith@smiths.com","order_number":"433659378839","po_number":' .
                '"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","recurring":{"acco' .
                'unt_vault_id":"11e95f8ec39de8fbdb0a4f1a","token_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"contact_id":"11e95f8ec39de8fbdb0a4f1a","account_vault_api_id":"token1234abcd",' .
                '"token_api_id":"token1234abcd","_joi":{"conditions":{}},"active":true,"descript' .
                'ion":"Description","end_date":"2021-12-01","installment_total_count":20,"interv' .
                'al":1,"interval_type":"d","location_id":"11e95f8ec39de8fbdb0a4f1a","notificatio' .
                'n_days":2,"payment_method":"cc","product_transaction_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a","recurring_api_id":"recurring123' .
                '4abcd","start_date":"2021-12-01","status":"active","transaction_amount":300,"te' .
                'rms_agree":true,"terms_agree_ip":"192.168.0.10","recurring_c1":"recurring custo' .
                'm data 1","recurring_c2":"recurring custom data 2","recurring_c3":"recurring cu' .
                'stom data 3","send_to_proc_as_recur":true,"tags":["Walk-in Customer"],"secondar' .
                'y_amount":100,"currency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":' .
                '"2021-12-01","created_ts":1422040992,"modified_ts":1422040992,"recurring_type_i' .
                'd":"i","installment_amount_total":99999999,"created_user_id":"11e95f8ec39de8fbd' .
                'b0a4f1a"},"recurring_number":1,"room_num":"303","room_rate":95,"save_account":f' .
                'alse,"save_account_title":"John Account","subtotal_amount":599,"surcharge_amoun' .
                't":100,"tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal",' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2}],"tax":0,"tip_amount":0,"transaction_amount":0,"secondary_amount":0,"transac' .
                'tion_api_id":"transaction-payment-abcd123","transaction_c1":"custom-data-1","tr' .
                'ansaction_c2":"custom-data-2","transaction_c3":"custom-data-3","bank_funded_onl' .
                'y_override":false,"allow_partial_authorization_override":false,"auto_decline_cv' .
                'v_override":false,"auto_decline_street_override":false,"auto_decline_zip_overri' .
                'de":false,"ebt_type":"food_stamp","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":' .
                '1422040992,"modified_ts":1422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f1a","a' .
                'ccount_holder_name":"smith","account_type":"checking","token_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","ach_identifier":"P","ach_sec_code":"C21","auth_amount":1,"auth_co' .
                'de":"BR349K","avs":"BAD","avs_enhanced":"N","cardholder_present":true,"card_pre' .
                'sent":true,"check_number":"8520748520963","customer_ip":"192.168.0.10","cvv_res' .
                'ponse":"N","entry_mode_id":"C","emv_receipt_data":{"AID":"a0000000042203","APPL' .
                'AB":"US Maestro","APPN":"US Maestro","CVM":"Pin Verified","TSI":"e800","TVR":"0' .
                '800008000"},"first_six":"545454","last_four":"5454","payment_method":"cc","term' .
                'inal_serial_number":"1234567890","transaction_settlement_status":null,"charge_b' .
                'ack_date":"2021-12-01","is_recurring":true,"notification_email_sent":true,"par"' .
                ':"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"recurring_id":"11e95f8e' .
                'c39de8fbdb0a4f1a","settle_date":"2021-12-01","status_code":101,"transaction_bat' .
                'ch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED","voucher_number":"1234"' .
                ',"void_date":"2021-12-01","batch":"2","terms_agree":true,"response_message":nul' .
                'l,"return_date":"2021-12-01","trx_source_id":8,"routing_number":"051904524","tr' .
                'x_source_code":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a","is_accountvault":true' .
                ',"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","effective_date":"2021-12-01","is_token":true,"account_vault_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'account_vault":{"account_holder_name":"John Smith","account_vault_api_id":"acco' .
                'untvaultabcd","token_api_id":"tokenabcd","accountvault_c1":"accountvault custom' .
                ' 1","accountvault_c2":"accountvault custom 2","accountvault_c3":"accountvault c' .
                'ustom 3","token_c1":"token custom 1","token_c2":"token custom 2","token_c3":"to' .
                'ken custom 3","ach_sec_code":"WEB","billing_address":{"city":"Novi","state":"Mi' .
                'chigan","postal_code":"48375","phone":"3339998822","country":"USA"},"contact_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","identity_verification":{"d' .
                'l_state":"MI","dl_number":"1235567","ssn4":"8527","dob_year":"1980"},"location_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault_api_id":"previousaccount' .
                'vault123456","previous_token_api_id":"previousaccountvault123456","previous_acc' .
                'ount_vault_id":"11e95f8ec39de8fbdb0a4f1a","previous_token_id":"11e95f8ec39de8fb' .
                'db0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f1a","account_number"' .
                ':"545454545454545","terms_agree":true,"terms_agree_ip":"192.168.0.10","title":"' .
                'Test CC Account","token_import_id":"11e95f8ec39de8fbdb0a4f1a","secure_directory' .
                '_server_transaction_id":"d65e93c3-35ab-41ba-b307-767bfc19eae","secure_protocol_' .
                'version":2,"secure_auth_data":"vVwL7UNHCf8W8M2LAfvRChNHN7c%3D","secure_collecti' .
                'on_indicator":null,"three_ds_server_trans_id":"d65e93c3-35ab-41ba-b307-767bfc19' .
                'eae","acs_transaction_id":"13c701a3-5a88-4c45-89e9-ef65e50a8bf9","_joi":{},"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","account_type":"checking","active":true,"cau_summar' .
                'y_status_id":1,"created_ts":1422040992,"e_serial_number":"1234567890","e_track_' .
                'data":null,"e_format":null,"e_keyed_data":null,"expiring_in_months":null,"exp_d' .
                'ate":"0722","first_six":"700953","has_recurring":false,"last_four":"3657","modi' .
                'fied_ts":1422040992,"payment_method":"cc","ticket":null,"track_data":null,"crea' .
                'ted_user_id":"11e95f8ec39de8fbdb0a4f1a","cau_last_updated_ts":1422040992,"routi' .
                'ng_number":"051904524"},"quick_invoice":{"location_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","title":"My terminal","cc_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"ach_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","due_date":"2021-12-01' .
                '","item_list":[{"name":"Bread","amount":2015}],"allow_overpayment":true,"bank_f' .
                'unded_only_override":true,"email":"email@domain.com","contact_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","contact_api_id":"contact12345","quick_invoice_api_id":"quickinvo' .
                'ice12345","customer_id":"11e95f8ec39de8fbdb0a4f1a","expire_date":"2021-12-01","' .
                'allow_partial_pay":true,"attach_files_to_email":true,"send_email":true,"invoice' .
                '_number":"invoice12345","item_header":"Quick invoice header sample","item_foote' .
                'r":"Thank you","amount_due":245.36,"notification_email":"email@domain.com","sta' .
                'tus_id":1,"status_code":1,"note":"some note","notification_days_before_due_date' .
                '":3,"notification_days_after_due_date":7,"notification_on_due_date":true,"send_' .
                'text_to_pay":true,"files":[{}],"remaining_balance":245.36,"single_payment_min_a' .
                'mount":500,"single_payment_max_amount":500000,"cell_phone":"3339998822","tags":' .
                '["Walk-in Customer"],"quick_invoice_c1":"custom-data-1","quick_invoice_c2":"cus' .
                'tom-data-2","quick_invoice_c3":"custom-data-3","auto_reopen":true,"id":"11e95f8' .
                'ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"active":true,"payment_status_id":1,"is_active":true},"log_emails":[{"subject"' .
                ':"Payment Receipt - 12skiestech","body":"This email is being sent from a server' .
                '.","source_address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return' .
                '_path":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"01000' .
                '17e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","reason_sent":"Contact Email","reason_model":"Transaction","re' .
                'ason_model_id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@ze' .
                'amster.com>","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"is_void' .
                'able":true,"is_reversible":true,"is_refundable":true,"is_completable":true,"is_' .
                'settled":true,"created_user":{"account_number":"5454545454545454","branding_dom' .
                'ain_url":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fort' .
                'is Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth' .
                '":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com' .
                '","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_' .
                'name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"' .
                '5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":nul' .
                'l,"terms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_' .
                'page":"dashboard","page_size":2,"report_export_type":"csv","process_method":"vi' .
                'rtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{use' .
                'r_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_' .
                'code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","status_code":1,"api_only":false,"is_invitation":false,"address":{"city":"Nov' .
                'i","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0' .
                'a4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts"' .
                ':1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date' .
                '_time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_response_' .
                'body_ts":1422040992},"location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1' .
                '422040992,"modified_ts":1422040992,"account_number":"5454545454545454","address' .
                '":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_d' .
                'omain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"' .
                'default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda"' .
                ',"email_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"loca' .
                'tion-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custo' .
                'm 1","location_c2":"custom 2","location_c3":"custom data 3","name":"Sample Comp' .
                'any Headquarters","office_phone":"2481234567","office_ext_phone":"1021021209","' .
                'tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_not' .
                'es":true,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"location_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4","additi' .
                'onal_access":{}},"contact":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_n' .
                'umber":"54545433332","contact_api_id":"137","first_name":"John","last_name":"Sm' .
                'ith","cell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state' .
                '":"Michigan","postal_code":"48375","country":"USA"},"company_name":"Fortis Paym' .
                'ent Systems, LLC","header_message":"This is a sample message for you","date_of_' .
                'birth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_' .
                'phone":"3339998822","office_phone_ext":"5","home_phone_country_code":"+1","offi' .
                'ce_phone_country_code":"+1","cell_phone_country_code":"+1","header_message_type' .
                '":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3' .
                '":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com"' .
                ',"token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","' .
                'created_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a"},"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","cr' .
                'eated_ts":1422040992,"action":"CREATE","model":"TransactionRequest","model_id":' .
                '"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_deta' .
                'ils":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","field":"next_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8' .
                'fbdb0a4f1a","username":"email@domain.com","first_name":"Bob","last_name":"Fairv' .
                'iew"}}],"product_transaction":{"processor_version":"1_0_0","title":"My terminal' .
                '","payment_method":"cc","processor":"zgate","mcc":"1111","tax_surcharge_config"' .
                ':2,"partner":"standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":' .
                '{},"processor_data":{},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enabl' .
                'e_tip":true,"ach_allow_debit":true,"ach_allow_credit":true,"ach_allow_refund":t' .
                'rue,"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable' .
                '":true,"receipt_show_contact_name":true,"display_avs":true,"card_type_visa":tru' .
                'e,"card_type_mc":true,"card_type_disc":true,"card_type_amex":true,"card_type_di' .
                'ners":true,"card_type_jcb":true,"card_type_ebt":true,"allow_ebt_cash_benefit":t' .
                'rue,"allow_ebt_food_stamp":true,"invoice_location":true,"allow_partial_authoriz' .
                'ation":true,"allow_recurring_partial_authorization":true,"auto_decline_cvv":tru' .
                'e,"auto_decline_street":true,"auto_decline_zip":true,"split_payments_allow":tru' .
                'e,"vt_show_custom_fields":true,"receipt_show_custom_fields":true,"vt_override_s' .
                'ales_tax_allowed":true,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_req' .
                'uire_street":true,"auto_decline_cavv":true,"current_batch":34,"dup_check_per_ba' .
                'tch":null,"paylink_allow":false,"quick_invoice_allow":false,"level3_allow":fals' .
                'e,"payfac_enable":false,"enable_3ds":false,"sales_office_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","hosted_payment_page_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","allow_big_commerce":false,"level3_default":{"destination_country_code":"' .
                '840","duty_amount":0,"freight_amount":0,"national_tax":2,"sales_tax":200,"shipf' .
                'rom_zip_code":"AZ12345","shipto_zip_code":"MI48335","tax_amount":0,"tax_exempt"' .
                ':"0","customer_vat_registration":"12345678","merchant_vat_registration":"123456' .
                '","order_date":"171006","summary_commodity_code":"C1K2","tax_rate":0,"unique_va' .
                't_ref_number":"vat1234","line_items":[{"alternate_tax_id":"1234","debit_credit"' .
                ':"C","description":"cool drink","discount_amount":10,"discount_rate":11,"produc' .
                't_code":"coke12345678","quantity":5,"tax_amount":3,"tax_rate":0,"tax_type_appli' .
                'ed":"22","tax_type_id":"a1","unit_code":"gll","unit_cost":10,"commodity_code":"' .
                'cc123456","other_tax_amount":0}]},"cau_subscribe_type_id":0,"location_billing_a' .
                'ccount_id":"11eb88b873980c64a21e5fd2","product_billing_group_id":"nofees","acco' .
                'unt_number":"12345678","run_avs_on_accountvault_create":false,"accountvault_exp' .
                'ire_notification_email_enable":false,"debit_allow_void":false,"quick_invoice_te' .
                'xt_to_pay":false,"sms_enable":false,"vt_show_currency":true,"receipt_show_curre' .
                'ncy":false,"allow_blind_refund":false,"vt_show_company_name":false,"receipt_sho' .
                'w_company_name":false,"bank_funded_only":false,"require_cvv_on_keyed_cnp":true,' .
                '"require_cvv_on_tokenized_cnp":true,"show_secondary_amount":false,"allow_second' .
                'ary_amount":false,"show_google_pay":true,"show_apple_pay":true,"batch_risk_conf' .
                'ig":{},"currency_code":840,"enable_ach_validation":false,"enable_ach_retry":fal' .
                'se,"allow_softpos":false,"id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created' .
                '_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_api_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amount_allowed":false,"fortis_id":"' .
                '8149742","product_billing_group_code":"nofees","cau_subscribe_type_code":0},"al' .
                'l_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"t' .
                'agTransactions":[{"id":"11e95f8ec39de8fbdb0a4f1a","tag_id":"Tag ID","transactio' .
                'n_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":14220409' .
                '92,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39' .
                'de8fbdb0a4f1a"}],"declined_recurring_notification":{"id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modi' .
                'fied_ts":1422040992,"modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"payment_rec' .
                'urring_notification":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"' .
                'created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_ts":1422040992,"modified_' .
                'user_id":"11e95f8ec39de8fbdb0a4f1a"},"developer_company":{"title":"My terminal"' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modifie' .
                'd_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a"},"terminal":{"location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","default_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","terminal_appli' .
                'cation_id":"11e95f8ec39de8fbdb0a4f1a","terminal_cvm_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","terminal_manufacturer_code":"1","title":"My terminal","mac_address":"3D:F2' .
                ':C9:A6:B3:4F","local_ip_address":"192.168.0.10","port":10009,"serial_number":"1' .
                '234567890","terminal_number":"973456789012367","terminal_timeouts":{"card_entry' .
                '_timeout":47,"device_terms_prompt_timeout":30,"overall_timeout":125,"pin_entry_' .
                'timeout":40,"signature_input_timeout":35,"signature_submit_timeout":38,"status_' .
                'display_time":12,"tip_cashback_timeout":25,"transaction_timeout":17},"tip_perce' .
                'nts":{"percent_1":0,"percent_2":2,"percent_3":99},"header_line_1":"line 1 sampl' .
                'e","header_line_2":"line 2 sample","header_line_3":"line 3 sample","header_line' .
                '_4":"line 4 sample","header_line_5":"line 5 sample","trailer_line_1":"trailer 1' .
                ' sample","trailer_line_2":"trailer 2 sample","trailer_line_3":"trailer 3 sample' .
                '","trailer_line_4":"trailer 4 sample","trailer_line_5":"trailer 5 sample","defa' .
                'ult_checkin":"2021-12-01","default_checkout":"2021-12-01","default_room_rate":5' .
                '6,"default_room_number":"303","debit":false,"emv":false,"cashback_enable":false' .
                ',"print_enable":false,"sig_capture_enable":false,"is_provisioned":false,"tip_en' .
                'able":false,"validated_decryption":false,"communication_type":"http","active":t' .
                'rue,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":14220' .
                '40992,"last_registration_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"hosted_payment_page":{"us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","location_id":"11e95f8ec39de8fbdb0a4f1a","loc' .
                'ation_api_id":null,"product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","title":' .
                '"Sample title","redirect_url_delay":15,"min_payment_amount":0,"max_payment_amou' .
                'nt":9999999999,"redirect_url_on_approve":null,"redirect_url_on_decline":null,"f' .
                'ield_configuration":{"css_mini":true,"stack":"vertical","header":{"settings":{"' .
                'enabled":true,"columns":1,"rows":1},"fields":[{"id":"transaction_amount","label' .
                '":"Header","field_type":"heading","position":["1"],"required":true,"readonly":t' .
                'rue,"visible":true}]},"body":{"settings":{"enabled":true,"columns":1,"rows":1},' .
                '"fields":[{"id":"transaction_amount","label":"Header","field_type":"heading","p' .
                'osition":["1"],"required":true,"readonly":true,"visible":true}]},"footer":{"set' .
                'tings":{"enabled":true,"columns":1,"rows":1},"fields":[{"id":"transaction_amoun' .
                't","label":"Header","field_type":"heading","position":["1"],"required":true,"re' .
                'adonly":true,"visible":true}]}},"encryption_key":null,"stylesheet_url":null,"pa' .
                'rent_send_message":true,"hide_optional_fields":true,"id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"transaction' .
                '_level3":{"id":"11e95f8ec39de8fbdb0a4f1a","transaction_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","level3_data":{"destination_country_code":"840","duty_amount":0,"freight' .
                '_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ1234","shipt' .
                'o_zip_code":"FL1234","tax_amount":10,"tax_exempt":"0","customer_vat_registratio' .
                'n":"12345678","merchant_vat_registration":"123456","order_date":"171006","summa' .
                'ry_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","line_' .
                'items":[{"description":"cool drink","commodity_code":"cc123456","discount_amoun' .
                't":0,"other_tax_amount":0,"product_code":"fanta123456","quantity":12,"tax_amoun' .
                't":4,"tax_rate":0,"unit_code":"gll","unit_cost":3,"alternate_tax_id":"1234","de' .
                'bit_credit":"C","discount_rate":11,"tax_type_applied":"22","tax_type_id":"11"}]' .
                '}},"developer_company_id":"Sample Developer Company ID","transaction_histories"' .
                ':[{"transaction_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"status_id":101,"event_date_ts":1422040992,"location_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992,"modified_ts":1422040992}],"surcharge_transaction"' .
                ':{"id":"11e95f8ec39de8fbdb0a4f1a","model_name":"Model Name","transaction_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","surcharge_fee":0,"surcharge_rate":0,"surcharge_amount' .
                '":null,"surcharge_transaction_min":null,"surcharge_transaction_max":null,"creat' .
                'ed":1422040992,"modified":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"surcharge":{"surcharge_fee":' .
                '10,"surcharge_rate":1,"product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","appl' .
                'y_to_user_type_id":"11e95f8ec39de8fbdb0a4f1a","title":null,"surcharge_label":nu' .
                'll,"surcharge_transaction_product_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8e' .
                'c39de8fbdb0a4f1a","created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}' .
                ',"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvklE' .
                'QVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5s5MwZ' .
                '39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6WCxURDTLsqmngz' .
                'cgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCzLm5j68Q1Fx2o3T' .
                'wTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqfeQ/bzHkgOIf0VzHP' .
                '83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU3T9jVbTLcRnMO620e' .
                'zep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1UpFRPf7ffveuq41Td' .
                'OHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUpoV' .
                'rsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9WqbFR' .
                'PaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zPnKlbD' .
                'Guvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsym+' .
                'DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEcYBHBA' .
                'RYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC0ah++pNrAAAA' .
                'AElFTkSuQmCC","resource":"Transaction","resource_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":14220409' .
                '92},"reason_code":{"id":50,"title":"Sample Title"},"type":{"id":50,"title":"Sam' .
                'ple Title"},"status":{"id":50,"title":"Sample Title"},"transaction_batch":{"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"product_transaction_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","processing_status_id":2,"batch_num":4,"is_open":0,"se' .
                'ttlement_file_name":"settement_file.txt","batch_close_ts":1531423693,"batch_clo' .
                'se_detail":"BATCH_MISMATCH","total_sale_amount":2342,"total_sale_count":21,"tot' .
                'al_refund_amount":2342,"total_refund_count":18,"total_void_amount":2342,"total_' .
                'void_count":17,"total_blind_refund_amount":2342,"total_blind_refund_count":16},' .
                '"transaction_splits":[{"transaction_id":"11e95f8ec39de8fbdb0a4f1a","contact_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","amount":10,"id":"11e95f8ec39de8fbdb0a4f1a","create' .
                'd_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"postback_logs"' .
                ':[{"id":"11e95f8ec39de8fbdb0a4f1a","postback_config_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","next_run_ts":1422040992,"created' .
                '_ts":1422040992,"model_id":"11e95f8ec39de8fbdb0a4f1a"}],"currency_type":{"id":5' .
                '0,"title":"Sample Title"},"transaction_references":[{"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"r' .
                'ejected_transaction_ach_retries":[{"rejected_transaction_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","retry_transaction_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","return_fee_transaction_id":"11e95f8ec39de8fbdb0a4f1a","created_ts"' .
                ':1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"return_fee_transact' .
                'ion_ach_retry":{"rejected_transaction_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","retry_transaction_id":"11e95f8ec39de8fbdb0a4f1a","return' .
                '_fee_transaction_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"create' .
                'd_user_id":"11e95f8ec39de8fbdb0a4f1a"},"retry_transaction_ach_retry":{"rejected' .
                '_transaction_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","re' .
                'try_transaction_id":"11e95f8ec39de8fbdb0a4f1a","return_fee_transaction_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a"},"saved_account":{"account_holder_name":"John Smith","account_vaul' .
                't_api_id":"accountvaultabcd","token_api_id":"tokenabcd","accountvault_c1":"acco' .
                'untvault custom 1","accountvault_c2":"accountvault custom 2","accountvault_c3":' .
                '"accountvault custom 3","token_c1":"token custom 1","token_c2":"token custom 2"' .
                ',"token_c3":"token custom 3","ach_sec_code":"WEB","billing_address":{"city":"No' .
                'vi","state":"Michigan","postal_code":"48375","phone":"3339998822","country":"US' .
                'A"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","identity_ve' .
                'rification":{"dl_state":"MI","dl_number":"1235567","ssn4":"8527","dob_year":"19' .
                '80"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault_api_id":"' .
                'previousaccountvault123456","previous_token_api_id":"previousaccountvault123456' .
                '","previous_account_vault_id":"11e95f8ec39de8fbdb0a4f1a","previous_token_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'account_number":"545454545454545","terms_agree":true,"terms_agree_ip":"192.168.' .
                '0.10","title":"Test CC Account","token_import_id":"11e95f8ec39de8fbdb0a4f1a","s' .
                'ecure_directory_server_transaction_id":"d65e93c3-35ab-41ba-b307-767bfc19eae","s' .
                'ecure_protocol_version":2,"secure_auth_data":"vVwL7UNHCf8W8M2LAfvRChNHN7c%3D","' .
                'secure_collection_indicator":null,"three_ds_server_trans_id":"d65e93c3-35ab-41b' .
                'a-b307-767bfc19eae","acs_transaction_id":"13c701a3-5a88-4c45-89e9-ef65e50a8bf9"' .
                ',"_joi":{},"id":"11e95f8ec39de8fbdb0a4f1a","account_type":"checking","active":t' .
                'rue,"cau_summary_status_id":1,"created_ts":1422040992,"e_serial_number":"123456' .
                '7890","e_track_data":null,"e_format":null,"e_keyed_data":null,"expiring_in_mont' .
                'hs":null,"exp_date":"0722","first_six":"700953","has_recurring":false,"last_fou' .
                'r":"3657","modified_ts":1422040992,"payment_method":"cc","ticket":null,"track_d' .
                'ata":null,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","cau_last_updated_ts":14' .
                '22040992,"routing_number":"051904524"},"balances":[{"amount":1000}]}}'
            )))
            ->assert();
    }
}
