<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\UsersController;
use FortisAPILib\Exceptions;

class UsersControllerTest extends BaseTestController
{
    /**
     * @var UsersController UsersController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getUsersController();
    }

    public function testCreateANewAPIKey()
    {
        // Parameters for the API call
        $userId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createANewAPIKey($userId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(201)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(
                TestParam::object('{"type":"UserApiKey","data":{"user_api_key":"234bas8dfn8238f923w2"}}')
            ))
            ->assert();
    }

    public function testListAllUser()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllUser(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"UsersCollection","list":[{"account_number":"5454545454545454","brandi' .
                'ng_domain_url":"{branding_domain_url}","cell_phone":"3339998822","company_name"' .
                ':"Fortis Payment Systems, LLC","contact_id":"Sample contact ID","date_of_birth"' .
                ':"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com"' .
                ',"email_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_n' .
                'ame":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"5' .
                '","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null' .
                ',"terms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_p' .
                'age":"dashboard","page_size":2,"report_export_type":"csv","process_method":"vir' .
                'tual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user' .
                '_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_c' .
                'ode":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"status_code":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi' .
                '","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":' .
                '1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_' .
                'time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_response_b' .
                'ody_ts":1422040992,"locations":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1' .
                '422040992,"modified_ts":1422040992,"account_number":"5454545454545454","address' .
                '":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_d' .
                'omain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"' .
                'default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda"' .
                ',"email_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"loca' .
                'tion-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custo' .
                'm 1","location_c2":"custom 2","location_c3":"custom data 3","name":"Sample Comp' .
                'any Headquarters","office_phone":"2481234567","office_ext_phone":"1021021209","' .
                'tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_not' .
                'es":true,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"location_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4","additi' .
                'onal_access":{}}],"primary_location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_' .
                'ts":1422040992,"modified_ts":1422040992,"account_number":"5454545454545454","ad' .
                'dress":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"brand' .
                'ing_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":t' .
                'rue,"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e09224' .
                '2dda","email_reply_to":"email@domain.com","fax":"3339998822","location_api_id":' .
                '"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"' .
                'custom 1","location_c2":"custom 2","location_c3":"custom data 3","name":"Sample' .
                ' Company Headquarters","office_phone":"2481234567","office_ext_phone":"10210212' .
                '09","tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contac' .
                't_notes":true,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","location_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4","a' .
                'dditional_access":{}},"received_emails":[{"subject":"Payment Receipt - 12skiest' .
                'ech","body":"This email is being sent from a server.","source_address":"\\"12sk' .
                'iestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3q' .
                'i\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a' .
                '5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sen' .
                't":"Contact Email","reason_model":"Transaction","reason_model_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec' .
                '39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"location_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","first_na' .
                'me":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.36,"addr' .
                'ess":{"city":"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"' .
                'company_name":"Fortis Payment Systems, LLC","header_message":"This is a sample ' .
                'message for you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_ph' .
                'one":"3339998822","office_phone":"3339998822","office_phone_ext":"5","home_phon' .
                'e_country_code":"+1","office_phone_country_code":"+1","cell_phone_country_code"' .
                ':"+1","header_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_' .
                'c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"acti' .
                've":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"isDeletable":true,"acti' .
                've_notification_alerts":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","date_start"' .
                ':"2021-12-01 10:10:00","date_end":"2021-12-01 10:10:00","user_location":true,"u' .
                'ser_contact":true,"include_children":true,"alert_type":1,"alert_type_id":1,"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a"}],"location_users":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","user_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"auth_role' .
                's":[{"user_id":"11e95f8ec39de8fbdb0a4f1a","auth_role_code":110,"code":83931,"cr' .
                'eated_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"changelogs":[{"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"' .
                'TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelo' .
                'g_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"' .
                '}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first' .
                '_name":"Bob","last_name":"Fairview"}}],"resources":{"title":"My terminal","priv' .
                '":null,"resource_name":"v2.addons.iframe.get","id":5693,"last_used_date":142204' .
                '0992,"created_ts":1422040992,"modified_ts":1422040992},"domain":{"url":"fortisp' .
                'ayrbyn9y.sandbox.zeamster.com","title":"Test Brand Domain Title 2","logo":"","s' .
                'upport_email":"email@domain.com","allow_contact_signup":true,"allow_contact_reg' .
                'istration":true,"allow_contact_login":true,"registration_fields":["account_numb' .
                'er"],"company_name":null,"nav_color":null,"button_primary_color":null,"logo_bac' .
                'kground_color":null,"icon_background_color":null,"menu_text_background_color":n' .
                'ull,"menu_text_color":null,"right_menu_background_color":null,"right_menu_text_' .
                'color":null,"button_primary_text_color":null,"nav_logo":null,"fav_icon":null,"a' .
                'es_key":null,"help_text":null,"email_reply_to":"email@domain.com","email":"emai' .
                'l@domain.com","custom_javascript":null,"custom_theme":null,"custom_css":null,"c' .
                'ontact_user_default_entry_page":"dashboard","contact_user_default_auth_roles":[' .
                'null],"custom_stylesheet_url":"https://127.0.0.1/receiver","id":"11e95f8ec39de8' .
                'fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992},"created_user":{"' .
                'account_number":"5454545454545454","branding_domain_url":"{branding_domain_url}' .
                '","cell_phone":"3339998822","company_name":"Fortis Payment Systems, LLC","conta' .
                'ct_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"hom' .
                'e_phone":"3339998822","first_name":"John","last_name":"Smith","locale":"en-US",' .
                '"office_phone":"3339998822","office_ext_phone":"5","primary_location_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_condition_code":"20220' .
                '308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2' .
                ',"report_export_type":"csv","process_method":"virtual_terminal","default_termin' .
                'al":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas' .
                '8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"password":null,"zip"' .
                ':"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":fa' .
                'lse,"is_invitation":false,"address":{"city":"Novi","state":"MI","postal_code":"' .
                '48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_att' .
                'empts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_ts":14220' .
                '40992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":14220409' .
                '92,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-070' .
                '0","current_login":1422040992,"log_api_response_body_ts":1422040992},"location_' .
                'marketplaces":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","marketplace_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","location_api_id":null,"user_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","' .
                'isBlacklisted":true,"detail":true,"created_ts":1422040992},"helppage":{"user_ty' .
                'pe_code":100,"body":"Sample Body","title":"Sample Title","id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}}],"link' .
                's":{"type":"Links","first":"/v1/endpoint?page[size]=10&page[number]=1","previou' .
                's":"/v1/endpoint?page[size]=10&page[number]=5","next":"/v1/endpoint?page[size]=' .
                '10&page[number]=7","last":"/v1/endpoint?page[size]=10&page[number]=42"},"pagina' .
                'tion":{"type":"Pagination","total_count":423,"page_count":42,"page_number":6,"p' .
                'age_size":10},"sort":{"type":"Sorting","fields":[{"field":"last_name","order":"' .
                'asc"}]}}'
            )))
            ->assert();
    }

    public function testDeleteAUserRecord()
    {
        // Parameters for the API call
        $userId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->deleteAUserRecord($userId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"User","data":{"account_number":"5454545454545454","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Pay' .
                'ment Systems, LLC","contact_id":"Sample contact ID","date_of_birth":"2021-12-01' .
                '","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_' .
                'receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith"' .
                ',"locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_l' .
                'ocation_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_cond' .
                'ition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashbo' .
                'ard","page_size":2,"report_export_type":"csv","process_method":"virtual_termina' .
                'l","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","use' .
                'r_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"pa' .
                'ssword":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_cod' .
                'e":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","state":"M' .
                'I","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","statu' .
                's":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"' .
                'modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_acc' .
                'epted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-' .
                '03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_ts":1422' .
                '040992,"locations":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"m' .
                'odified_ts":1422040992,"account_number":"5454545454545454","address":{"city":"N' .
                'ovi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach"' .
                ':"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_repl' .
                'y_to":"email@domain.com","fax":"3339998822","location_api_id":"location-111111"' .
                ',"location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","locati' .
                'on_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Headquar' .
                'ters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"America' .
                '/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"sh' .
                'ow_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_t' .
                'ype":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4","additional_access"' .
                ':{}}],"primary_location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"modified_ts":1422040992,"account_number":"5454545454545454","address":{"cit' .
                'y":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default' .
                '_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email' .
                '_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"location-11' .
                '1111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","l' .
                'ocation_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Hea' .
                'dquarters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"Am' .
                'erica/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":tru' .
                'e,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","locat' .
                'ion_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4","additional_ac' .
                'cess":{}},"received_emails":[{"subject":"Payment Receipt - 12skiestech","body":' .
                '"This email is being sent from a server.","source_address":"\\"12skiestech A7t3' .
                'qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi\\" <norepl' .
                'y@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d5' .
                '1c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent":"Contact ' .
                'Email","reason_model":"Transaction","reason_model_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992}],"contact":{"location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_number":"54545433332","contact_api_id":"137","first_name":"John","' .
                'last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city"' .
                ':"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"company_name' .
                '":"Fortis Payment Systems, LLC","header_message":"This is a sample message for ' .
                'you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999' .
                '8822","office_phone":"3339998822","office_phone_ext":"5","home_phone_country_co' .
                'de":"+1","office_phone_country_code":"+1","cell_phone_country_code":"+1","heade' .
                'r_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anythin' .
                'g","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"ema' .
                'il@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de' .
                '8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,"cr' .
                'eated_user_id":"11e95f8ec39de8fbdb0a4f1a"},"isDeletable":true,"active_notificat' .
                'ion_alerts":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","date_start":"2021-12-01' .
                ' 10:10:00","date_end":"2021-12-01 10:10:00","user_location":true,"user_contact"' .
                ':true,"include_children":true,"alert_type":1,"alert_type_id":1,"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],' .
                '"location_users":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","user_id":"11e95f8e' .
                'c39de8fbdb0a4f1a","location_api_id":null,"id":"11e95f8ec39de8fbdb0a4f1a","creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"auth_roles":[{"user_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","auth_role_code":110,"code":83931,"created_ts":14' .
                '22040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"changelogs":[{"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"TransactionR' .
                'equest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user":{"' .
                'id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_name":"Bob"' .
                ',"last_name":"Fairview"}}],"resources":{"title":"My terminal","priv":null,"reso' .
                'urce_name":"v2.addons.iframe.get","id":5693,"last_used_date":1422040992,"create' .
                'd_ts":1422040992,"modified_ts":1422040992},"domain":{"url":"fortispayrbyn9y.san' .
                'dbox.zeamster.com","title":"Test Brand Domain Title 2","logo":"","support_email' .
                '":"email@domain.com","allow_contact_signup":true,"allow_contact_registration":t' .
                'rue,"allow_contact_login":true,"registration_fields":["account_number"],"compan' .
                'y_name":null,"nav_color":null,"button_primary_color":null,"logo_background_colo' .
                'r":null,"icon_background_color":null,"menu_text_background_color":null,"menu_te' .
                'xt_color":null,"right_menu_background_color":null,"right_menu_text_color":null,' .
                '"button_primary_text_color":null,"nav_logo":null,"fav_icon":null,"aes_key":null' .
                ',"help_text":null,"email_reply_to":"email@domain.com","email":"email@domain.com' .
                '","custom_javascript":null,"custom_theme":null,"custom_css":null,"contact_user_' .
                'default_entry_page":"dashboard","contact_user_default_auth_roles":[null],"custo' .
                'm_stylesheet_url":"https://127.0.0.1/receiver","id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"created_ts":1422040992,"modified_ts":1422040992},"created_user":{"account_numb' .
                'er":"5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phon' .
                'e":"3339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"33' .
                '39998822","first_name":"John","last_name":"Smith","locale":"en-US","office_phon' .
                'e":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"A' .
                'merica/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_exp' .
                'ort_type":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8' .
                'ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923' .
                'w2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","lo' .
                'cation_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invi' .
                'tation":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","coun' .
                'try":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"la' .
                'st_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"creat' .
                'ed_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_ag' .
                'ree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_' .
                'login":1422040992,"log_api_response_body_ts":1422040992},"location_marketplaces' .
                '":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","marketplace_id":"11e95f8ec39de8fb' .
                'db0a4f1a","location_api_id":null,"user_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e' .
                '95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlackliste' .
                'd":true,"detail":true,"created_ts":1422040992},"helppage":{"user_type_code":100' .
                ',"body":"Sample Body","title":"Sample Title","id":"11e95f8ec39de8fbdb0a4f1a","c' .
                'reated_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }

    public function testViewSingleUserRecord()
    {
        // Parameters for the API call
        $userId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleUserRecord($userId, $expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"User","data":{"account_number":"5454545454545454","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Pay' .
                'ment Systems, LLC","contact_id":"Sample contact ID","date_of_birth":"2021-12-01' .
                '","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_' .
                'receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith"' .
                ',"locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_l' .
                'ocation_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_cond' .
                'ition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashbo' .
                'ard","page_size":2,"report_export_type":"csv","process_method":"virtual_termina' .
                'l","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","use' .
                'r_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"pa' .
                'ssword":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_cod' .
                'e":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","state":"M' .
                'I","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","statu' .
                's":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"' .
                'modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_acc' .
                'epted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-' .
                '03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_ts":1422' .
                '040992,"locations":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"m' .
                'odified_ts":1422040992,"account_number":"5454545454545454","address":{"city":"N' .
                'ovi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach"' .
                ':"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_repl' .
                'y_to":"email@domain.com","fax":"3339998822","location_api_id":"location-111111"' .
                ',"location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","locati' .
                'on_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Headquar' .
                'ters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"America' .
                '/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"sh' .
                'ow_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_t' .
                'ype":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4","additional_access"' .
                ':{}}],"primary_location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"modified_ts":1422040992,"account_number":"5454545454545454","address":{"cit' .
                'y":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default' .
                '_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email' .
                '_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"location-11' .
                '1111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","l' .
                'ocation_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Hea' .
                'dquarters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"Am' .
                'erica/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":tru' .
                'e,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","locat' .
                'ion_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4","additional_ac' .
                'cess":{}},"received_emails":[{"subject":"Payment Receipt - 12skiestech","body":' .
                '"This email is being sent from a server.","source_address":"\\"12skiestech A7t3' .
                'qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi\\" <norepl' .
                'y@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d5' .
                '1c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent":"Contact ' .
                'Email","reason_model":"Transaction","reason_model_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992}],"contact":{"location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_number":"54545433332","contact_api_id":"137","first_name":"John","' .
                'last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city"' .
                ':"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"company_name' .
                '":"Fortis Payment Systems, LLC","header_message":"This is a sample message for ' .
                'you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999' .
                '8822","office_phone":"3339998822","office_phone_ext":"5","home_phone_country_co' .
                'de":"+1","office_phone_country_code":"+1","cell_phone_country_code":"+1","heade' .
                'r_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anythin' .
                'g","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"ema' .
                'il@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de' .
                '8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,"cr' .
                'eated_user_id":"11e95f8ec39de8fbdb0a4f1a"},"isDeletable":true,"active_notificat' .
                'ion_alerts":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","date_start":"2021-12-01' .
                ' 10:10:00","date_end":"2021-12-01 10:10:00","user_location":true,"user_contact"' .
                ':true,"include_children":true,"alert_type":1,"alert_type_id":1,"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],' .
                '"location_users":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","user_id":"11e95f8e' .
                'c39de8fbdb0a4f1a","location_api_id":null,"id":"11e95f8ec39de8fbdb0a4f1a","creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"auth_roles":[{"user_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","auth_role_code":110,"code":83931,"created_ts":14' .
                '22040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"changelogs":[{"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"TransactionR' .
                'equest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user":{"' .
                'id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_name":"Bob"' .
                ',"last_name":"Fairview"}}],"resources":{"title":"My terminal","priv":null,"reso' .
                'urce_name":"v2.addons.iframe.get","id":5693,"last_used_date":1422040992,"create' .
                'd_ts":1422040992,"modified_ts":1422040992},"domain":{"url":"fortispayrbyn9y.san' .
                'dbox.zeamster.com","title":"Test Brand Domain Title 2","logo":"","support_email' .
                '":"email@domain.com","allow_contact_signup":true,"allow_contact_registration":t' .
                'rue,"allow_contact_login":true,"registration_fields":["account_number"],"compan' .
                'y_name":null,"nav_color":null,"button_primary_color":null,"logo_background_colo' .
                'r":null,"icon_background_color":null,"menu_text_background_color":null,"menu_te' .
                'xt_color":null,"right_menu_background_color":null,"right_menu_text_color":null,' .
                '"button_primary_text_color":null,"nav_logo":null,"fav_icon":null,"aes_key":null' .
                ',"help_text":null,"email_reply_to":"email@domain.com","email":"email@domain.com' .
                '","custom_javascript":null,"custom_theme":null,"custom_css":null,"contact_user_' .
                'default_entry_page":"dashboard","contact_user_default_auth_roles":[null],"custo' .
                'm_stylesheet_url":"https://127.0.0.1/receiver","id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"created_ts":1422040992,"modified_ts":1422040992},"created_user":{"account_numb' .
                'er":"5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phon' .
                'e":"3339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"33' .
                '39998822","first_name":"John","last_name":"Smith","locale":"en-US","office_phon' .
                'e":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"A' .
                'merica/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_exp' .
                'ort_type":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8' .
                'ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923' .
                'w2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","lo' .
                'cation_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invi' .
                'tation":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","coun' .
                'try":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"la' .
                'st_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"creat' .
                'ed_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_ag' .
                'ree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_' .
                'login":1422040992,"log_api_response_body_ts":1422040992},"location_marketplaces' .
                '":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","marketplace_id":"11e95f8ec39de8fb' .
                'db0a4f1a","location_api_id":null,"user_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e' .
                '95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlackliste' .
                'd":true,"detail":true,"created_ts":1422040992},"helppage":{"user_type_code":100' .
                ',"body":"Sample Body","title":"Sample Title","id":"11e95f8ec39de8fbdb0a4f1a","c' .
                'reated_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }

    public function testViewSelfRecord()
    {
        // Parameters for the API call
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSelfRecord($expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"User","data":{"account_number":"5454545454545454","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Pay' .
                'ment Systems, LLC","contact_id":"Sample contact ID","date_of_birth":"2021-12-01' .
                '","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_' .
                'receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith"' .
                ',"locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_l' .
                'ocation_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_cond' .
                'ition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashbo' .
                'ard","page_size":2,"report_export_type":"csv","process_method":"virtual_termina' .
                'l","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","use' .
                'r_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"pa' .
                'ssword":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_cod' .
                'e":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","state":"M' .
                'I","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","statu' .
                's":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"' .
                'modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_acc' .
                'epted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-' .
                '03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_ts":1422' .
                '040992,"locations":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"m' .
                'odified_ts":1422040992,"account_number":"5454545454545454","address":{"city":"N' .
                'ovi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach"' .
                ':"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_repl' .
                'y_to":"email@domain.com","fax":"3339998822","location_api_id":"location-111111"' .
                ',"location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","locati' .
                'on_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Headquar' .
                'ters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"America' .
                '/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"sh' .
                'ow_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_t' .
                'ype":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4","additional_access"' .
                ':{}}],"primary_location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"modified_ts":1422040992,"account_number":"5454545454545454","address":{"cit' .
                'y":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default' .
                '_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email' .
                '_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"location-11' .
                '1111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","l' .
                'ocation_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Hea' .
                'dquarters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"Am' .
                'erica/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":tru' .
                'e,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","locat' .
                'ion_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4","additional_ac' .
                'cess":{}},"received_emails":[{"subject":"Payment Receipt - 12skiestech","body":' .
                '"This email is being sent from a server.","source_address":"\\"12skiestech A7t3' .
                'qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi\\" <norepl' .
                'y@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d5' .
                '1c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent":"Contact ' .
                'Email","reason_model":"Transaction","reason_model_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992}],"contact":{"location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_number":"54545433332","contact_api_id":"137","first_name":"John","' .
                'last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city"' .
                ':"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"company_name' .
                '":"Fortis Payment Systems, LLC","header_message":"This is a sample message for ' .
                'you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999' .
                '8822","office_phone":"3339998822","office_phone_ext":"5","home_phone_country_co' .
                'de":"+1","office_phone_country_code":"+1","cell_phone_country_code":"+1","heade' .
                'r_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anythin' .
                'g","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"ema' .
                'il@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de' .
                '8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,"cr' .
                'eated_user_id":"11e95f8ec39de8fbdb0a4f1a"},"isDeletable":true,"active_notificat' .
                'ion_alerts":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","date_start":"2021-12-01' .
                ' 10:10:00","date_end":"2021-12-01 10:10:00","user_location":true,"user_contact"' .
                ':true,"include_children":true,"alert_type":1,"alert_type_id":1,"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],' .
                '"location_users":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","user_id":"11e95f8e' .
                'c39de8fbdb0a4f1a","location_api_id":null,"id":"11e95f8ec39de8fbdb0a4f1a","creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"auth_roles":[{"user_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","auth_role_code":110,"code":83931,"created_ts":14' .
                '22040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"changelogs":[{"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"TransactionR' .
                'equest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user":{"' .
                'id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_name":"Bob"' .
                ',"last_name":"Fairview"}}],"resources":{"title":"My terminal","priv":null,"reso' .
                'urce_name":"v2.addons.iframe.get","id":5693,"last_used_date":1422040992,"create' .
                'd_ts":1422040992,"modified_ts":1422040992},"domain":{"url":"fortispayrbyn9y.san' .
                'dbox.zeamster.com","title":"Test Brand Domain Title 2","logo":"","support_email' .
                '":"email@domain.com","allow_contact_signup":true,"allow_contact_registration":t' .
                'rue,"allow_contact_login":true,"registration_fields":["account_number"],"compan' .
                'y_name":null,"nav_color":null,"button_primary_color":null,"logo_background_colo' .
                'r":null,"icon_background_color":null,"menu_text_background_color":null,"menu_te' .
                'xt_color":null,"right_menu_background_color":null,"right_menu_text_color":null,' .
                '"button_primary_text_color":null,"nav_logo":null,"fav_icon":null,"aes_key":null' .
                ',"help_text":null,"email_reply_to":"email@domain.com","email":"email@domain.com' .
                '","custom_javascript":null,"custom_theme":null,"custom_css":null,"contact_user_' .
                'default_entry_page":"dashboard","contact_user_default_auth_roles":[null],"custo' .
                'm_stylesheet_url":"https://127.0.0.1/receiver","id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"created_ts":1422040992,"modified_ts":1422040992},"created_user":{"account_numb' .
                'er":"5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phon' .
                'e":"3339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"33' .
                '39998822","first_name":"John","last_name":"Smith","locale":"en-US","office_phon' .
                'e":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"A' .
                'merica/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_exp' .
                'ort_type":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8' .
                'ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923' .
                'w2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","lo' .
                'cation_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invi' .
                'tation":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","coun' .
                'try":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"la' .
                'st_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"creat' .
                'ed_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_ag' .
                'ree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_' .
                'login":1422040992,"log_api_response_body_ts":1422040992},"location_marketplaces' .
                '":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","marketplace_id":"11e95f8ec39de8fb' .
                'db0a4f1a","location_api_id":null,"user_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e' .
                '95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlackliste' .
                'd":true,"detail":true,"created_ts":1422040992},"helppage":{"user_type_code":100' .
                ',"body":"Sample Body","title":"Sample Title","id":"11e95f8ec39de8fbdb0a4f1a","c' .
                'reated_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }

    public function testRemoveVerification()
    {
        // Parameters for the API call
        $userId = '';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->removeVerification($userId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"RemoveVerification","data":{"id":"11e95f8ec39de8fbdb0a4f1a","user_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","hash":"123456781234567812345678","created_ts":1422' .
                '040992}}'
            )))
            ->assert();
    }

    public function testSendVerification()
    {
        // Parameters for the API call
        $userId = '';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->sendVerification($userId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(201)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"SendVerification","data":{"id":"11e95f8ec39de8fbdb0a4f1a","user_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","hash":"123456781234567812345678","created_ts":142204' .
                '0992}}'
            )))
            ->assert();
    }
}
