<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\BroadInfo;

/**
 * Builder for model BroadInfo
 *
 * @see BroadInfo
 */
class BroadInfoBuilder
{
    /**
     * @var BroadInfo
     */
    private $instance;

    private function __construct(BroadInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Broad Info Builder object.
     */
    public static function init(): self
    {
        return new self(new BroadInfo());
    }

    /**
     * Sets category field.
     *
     * @param string|null $value
     */
    public function category(?string $value): self
    {
        $this->instance->setCategory($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets expire date field.
     *
     * @param string|null $value
     */
    public function expireDate(?string $value): self
    {
        $this->instance->setExpireDate($value);
        return $this;
    }

    /**
     * Sets severity field.
     *
     * @param string|null $value
     */
    public function severity(?string $value): self
    {
        $this->instance->setSeverity($value);
        return $this;
    }

    /**
     * Sets recipients field.
     *
     * @param string|null $value
     */
    public function recipients(?string $value): self
    {
        $this->instance->setRecipients($value);
        return $this;
    }

    /**
     * Sets source field.
     *
     * @param string|null $value
     */
    public function source(?string $value): self
    {
        $this->instance->setSource($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Broad Info object.
     */
    public function build(): BroadInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
