<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\BillingAddress24;
use FortisAPILib\Models\Cardholder;
use FortisAPILib\Models\HomePhone;
use FortisAPILib\Models\MobilePhone;
use FortisAPILib\Models\ShippingAddress;
use FortisAPILib\Models\WorkPhone;

/**
 * Builder for model Cardholder
 *
 * @see Cardholder
 */
class CardholderBuilder
{
    /**
     * @var Cardholder
     */
    private $instance;

    private function __construct(Cardholder $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cardholder Builder object.
     */
    public static function init(): self
    {
        return new self(new Cardholder());
    }

    /**
     * Sets address match field.
     *
     * @param string|null $value
     */
    public function addressMatch(?string $value): self
    {
        $this->instance->setAddressMatch($value);
        return $this;
    }

    /**
     * Sets billing address field.
     *
     * @param BillingAddress24|null $value
     */
    public function billingAddress(?BillingAddress24 $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets home phone field.
     *
     * @param HomePhone|null $value
     */
    public function homePhone(?HomePhone $value): self
    {
        $this->instance->setHomePhone($value);
        return $this;
    }

    /**
     * Sets mobile phone field.
     *
     * @param MobilePhone|null $value
     */
    public function mobilePhone(?MobilePhone $value): self
    {
        $this->instance->setMobilePhone($value);
        return $this;
    }

    /**
     * Sets work phone field.
     *
     * @param WorkPhone|null $value
     */
    public function workPhone(?WorkPhone $value): self
    {
        $this->instance->setWorkPhone($value);
        return $this;
    }

    /**
     * Sets cardholder name field.
     *
     * @param string|null $value
     */
    public function cardholderName(?string $value): self
    {
        $this->instance->setCardholderName($value);
        return $this;
    }

    /**
     * Sets shipping address field.
     *
     * @param ShippingAddress|null $value
     */
    public function shippingAddress(?ShippingAddress $value): self
    {
        $this->instance->setShippingAddress($value);
        return $this;
    }

    /**
     * Sets tax id field.
     *
     * @param string|null $value
     */
    public function taxId(?string $value): self
    {
        $this->instance->setTaxId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Cardholder object.
     */
    public function build(): Cardholder
    {
        return CoreHelper::clone($this->instance);
    }
}
