<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Data39;
use FortisAPILib\Models\PostbackLog;

/**
 * Builder for model Data39
 *
 * @see Data39
 */
class Data39Builder
{
    /**
     * @var Data39
     */
    private $instance;

    private function __construct(Data39 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Data 39 Builder object.
     */
    public static function init(): self
    {
        return new self(new Data39());
    }

    /**
     * Sets attempt interval field.
     *
     * @param int|null $value
     */
    public function attemptInterval(?int $value): self
    {
        $this->instance->setAttemptInterval($value);
        return $this;
    }

    /**
     * Unsets attempt interval field.
     */
    public function unsetAttemptInterval(): self
    {
        $this->instance->unsetAttemptInterval();
        return $this;
    }

    /**
     * Sets basic auth username field.
     *
     * @param string|null $value
     */
    public function basicAuthUsername(?string $value): self
    {
        $this->instance->setBasicAuthUsername($value);
        return $this;
    }

    /**
     * Unsets basic auth username field.
     */
    public function unsetBasicAuthUsername(): self
    {
        $this->instance->unsetBasicAuthUsername();
        return $this;
    }

    /**
     * Sets basic auth password field.
     *
     * @param string|null $value
     */
    public function basicAuthPassword(?string $value): self
    {
        $this->instance->setBasicAuthPassword($value);
        return $this;
    }

    /**
     * Unsets basic auth password field.
     */
    public function unsetBasicAuthPassword(): self
    {
        $this->instance->unsetBasicAuthPassword();
        return $this;
    }

    /**
     * Sets expands field.
     *
     * @param string|null $value
     */
    public function expands(?string $value): self
    {
        $this->instance->setExpands($value);
        return $this;
    }

    /**
     * Unsets expands field.
     */
    public function unsetExpands(): self
    {
        $this->instance->unsetExpands();
        return $this;
    }

    /**
     * Sets format field.
     *
     * @param string|null $value
     */
    public function format(?string $value): self
    {
        $this->instance->setFormat($value);
        return $this;
    }

    /**
     * Unsets format field.
     */
    public function unsetFormat(): self
    {
        $this->instance->unsetFormat();
        return $this;
    }

    /**
     * Sets is active field.
     *
     * @param bool|null $value
     */
    public function isActive(?bool $value): self
    {
        $this->instance->setIsActive($value);
        return $this;
    }

    /**
     * Sets location id field.
     *
     * @param string|null $value
     */
    public function locationId(?string $value): self
    {
        $this->instance->setLocationId($value);
        return $this;
    }

    /**
     * Sets location api id field.
     *
     * @param string|null $value
     */
    public function locationApiId(?string $value): self
    {
        $this->instance->setLocationApiId($value);
        return $this;
    }

    /**
     * Unsets location api id field.
     */
    public function unsetLocationApiId(): self
    {
        $this->instance->unsetLocationApiId();
        return $this;
    }

    /**
     * Sets on create field.
     *
     * @param bool|null $value
     */
    public function onCreate(?bool $value): self
    {
        $this->instance->setOnCreate($value);
        return $this;
    }

    /**
     * Sets on update field.
     *
     * @param bool|null $value
     */
    public function onUpdate(?bool $value): self
    {
        $this->instance->setOnUpdate($value);
        return $this;
    }

    /**
     * Sets on delete field.
     *
     * @param bool|null $value
     */
    public function onDelete(?bool $value): self
    {
        $this->instance->setOnDelete($value);
        return $this;
    }

    /**
     * Sets legacy field.
     *
     * @param bool|null $value
     */
    public function legacy(?bool $value): self
    {
        $this->instance->setLegacy($value);
        return $this;
    }

    /**
     * Sets postback config id field.
     *
     * @param string|null $value
     */
    public function postbackConfigId(?string $value): self
    {
        $this->instance->setPostbackConfigId($value);
        return $this;
    }

    /**
     * Unsets postback config id field.
     */
    public function unsetPostbackConfigId(): self
    {
        $this->instance->unsetPostbackConfigId();
        return $this;
    }

    /**
     * Sets product transaction id field.
     *
     * @param string|null $value
     */
    public function productTransactionId(?string $value): self
    {
        $this->instance->setProductTransactionId($value);
        return $this;
    }

    /**
     * Unsets product transaction id field.
     */
    public function unsetProductTransactionId(): self
    {
        $this->instance->unsetProductTransactionId();
        return $this;
    }

    /**
     * Sets resource field.
     *
     * @param string|null $value
     */
    public function resource(?string $value): self
    {
        $this->instance->setResource($value);
        return $this;
    }

    /**
     * Sets number of attempts field.
     *
     * @param int|null $value
     */
    public function numberOfAttempts(?int $value): self
    {
        $this->instance->setNumberOfAttempts($value);
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets postback logs field.
     *
     * @param PostbackLog[]|null $value
     */
    public function postbackLogs(?array $value): self
    {
        $this->instance->setPostbackLogs($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Data 39 object.
     */
    public function build(): Data39
    {
        return CoreHelper::clone($this->instance);
    }
}
