<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Data17;

/**
 * Builder for model Data17
 *
 * @see Data17
 */
class Data17Builder
{
    /**
     * @var Data17
     */
    private $instance;

    private function __construct(Data17 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Data 17 Builder object.
     */
    public static function init(): self
    {
        return new self(new Data17());
    }

    /**
     * Sets token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Data 17 object.
     */
    public function build(): Data17
    {
        return CoreHelper::clone($this->instance);
    }
}
