<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Context;
use FortisAPILib\Models\Detail;

/**
 * Builder for model Detail
 *
 * @see Detail
 */
class DetailBuilder
{
    /**
     * @var Detail
     */
    private $instance;

    private function __construct(Detail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Detail Builder object.
     */
    public static function init(): self
    {
        return new self(new Detail());
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets path field.
     *
     * @param string[]|null $value
     */
    public function path(?array $value): self
    {
        $this->instance->setPath($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets context field.
     *
     * @param Context|null $value
     */
    public function context(?Context $value): self
    {
        $this->instance->setContext($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Detail object.
     */
    public function build(): Detail
    {
        return CoreHelper::clone($this->instance);
    }
}
