<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\File5;

/**
 * Builder for model File5
 *
 * @see File5
 */
class File5Builder
{
    /**
     * @var File5
     */
    private $instance;

    private function __construct(File5 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new File 5 Builder object.
     */
    public static function init(): self
    {
        return new self(new File5());
    }

    /**
     * Sets file name field.
     *
     * @param string|null $value
     */
    public function fileName(?string $value): self
    {
        $this->instance->setFileName($value);
        return $this;
    }

    /**
     * Unsets file name field.
     */
    public function unsetFileName(): self
    {
        $this->instance->unsetFileName();
        return $this;
    }

    /**
     * Sets content field.
     *
     * @param string|null $value
     */
    public function content(?string $value): self
    {
        $this->instance->setContent($value);
        return $this;
    }

    /**
     * Unsets content field.
     */
    public function unsetContent(): self
    {
        $this->instance->unsetContent();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new File 5 object.
     */
    public function build(): File5
    {
        return CoreHelper::clone($this->instance);
    }
}
