<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\MerchantRiskIndicator;

/**
 * Builder for model MerchantRiskIndicator
 *
 * @see MerchantRiskIndicator
 */
class MerchantRiskIndicatorBuilder
{
    /**
     * @var MerchantRiskIndicator
     */
    private $instance;

    private function __construct(MerchantRiskIndicator $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Merchant Risk Indicator Builder object.
     */
    public static function init(): self
    {
        return new self(new MerchantRiskIndicator());
    }

    /**
     * Sets ship indicator field.
     *
     * @param string|null $value
     */
    public function shipIndicator(?string $value): self
    {
        $this->instance->setShipIndicator($value);
        return $this;
    }

    /**
     * Sets delivery timeframe field.
     *
     * @param string|null $value
     */
    public function deliveryTimeframe(?string $value): self
    {
        $this->instance->setDeliveryTimeframe($value);
        return $this;
    }

    /**
     * Sets delivery email address field.
     *
     * @param string|null $value
     */
    public function deliveryEmailAddress(?string $value): self
    {
        $this->instance->setDeliveryEmailAddress($value);
        return $this;
    }

    /**
     * Sets reorder items ind field.
     *
     * @param string|null $value
     */
    public function reorderItemsInd(?string $value): self
    {
        $this->instance->setReorderItemsInd($value);
        return $this;
    }

    /**
     * Sets pre order purchase ind field.
     *
     * @param string|null $value
     */
    public function preOrderPurchaseInd(?string $value): self
    {
        $this->instance->setPreOrderPurchaseInd($value);
        return $this;
    }

    /**
     * Sets pre order date field.
     *
     * @param string|null $value
     */
    public function preOrderDate(?string $value): self
    {
        $this->instance->setPreOrderDate($value);
        return $this;
    }

    /**
     * Sets gift card amount field.
     *
     * @param int|null $value
     */
    public function giftCardAmount(?int $value): self
    {
        $this->instance->setGiftCardAmount($value);
        return $this;
    }

    /**
     * Sets gift card curr field.
     *
     * @param string|null $value
     */
    public function giftCardCurr(?string $value): self
    {
        $this->instance->setGiftCardCurr($value);
        return $this;
    }

    /**
     * Sets gift card count field.
     *
     * @param int|null $value
     */
    public function giftCardCount(?int $value): self
    {
        $this->instance->setGiftCardCount($value);
        return $this;
    }

    /**
     * Sets trans char field.
     *
     * @param string[]|null $value
     */
    public function transChar(?array $value): self
    {
        $this->instance->setTransChar($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Merchant Risk Indicator object.
     */
    public function build(): MerchantRiskIndicator
    {
        return CoreHelper::clone($this->instance);
    }
}
