<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\MessageExtension;

/**
 * Builder for model MessageExtension
 *
 * @see MessageExtension
 */
class MessageExtensionBuilder
{
    /**
     * @var MessageExtension
     */
    private $instance;

    private function __construct(MessageExtension $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Message Extension Builder object.
     */
    public static function init(): self
    {
        return new self(new MessageExtension());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets criticality indicator field.
     *
     * @param bool|null $value
     */
    public function criticalityIndicator(?bool $value): self
    {
        $this->instance->setCriticalityIndicator($value);
        return $this;
    }

    /**
     * Sets data field.
     *
     * @param array|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Message Extension object.
     */
    public function build(): MessageExtension
    {
        return CoreHelper::clone($this->instance);
    }
}
