<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Data27;
use FortisAPILib\Models\ResponseTransaction;

/**
 * Builder for model ResponseTransaction
 *
 * @see ResponseTransaction
 */
class ResponseTransactionBuilder
{
    /**
     * @var ResponseTransaction
     */
    private $instance;

    private function __construct(ResponseTransaction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Transaction Builder object.
     */
    public static function init(): self
    {
        return new self(new ResponseTransaction());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets data field.
     *
     * @param Data27|null $value
     */
    public function data(?Data27 $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Transaction object.
     */
    public function build(): ResponseTransaction
    {
        return CoreHelper::clone($this->instance);
    }
}
