<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\ThreeDsRequestorPriorAuthenticationInfo;

/**
 * Builder for model ThreeDsRequestorPriorAuthenticationInfo
 *
 * @see ThreeDsRequestorPriorAuthenticationInfo
 */
class ThreeDsRequestorPriorAuthenticationInfoBuilder
{
    /**
     * @var ThreeDsRequestorPriorAuthenticationInfo
     */
    private $instance;

    private function __construct(ThreeDsRequestorPriorAuthenticationInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Three Ds Requestor Prior Authentication Info Builder object.
     */
    public static function init(): self
    {
        return new self(new ThreeDsRequestorPriorAuthenticationInfo());
    }

    /**
     * Sets three ds req prior ref field.
     *
     * @param string|null $value
     */
    public function threeDsReqPriorRef(?string $value): self
    {
        $this->instance->setThreeDsReqPriorRef($value);
        return $this;
    }

    /**
     * Sets three ds req prior auth method field.
     *
     * @param string|null $value
     */
    public function threeDsReqPriorAuthMethod(?string $value): self
    {
        $this->instance->setThreeDsReqPriorAuthMethod($value);
        return $this;
    }

    /**
     * Sets three ds req prior auth timestamp field.
     *
     * @param string|null $value
     */
    public function threeDsReqPriorAuthTimestamp(?string $value): self
    {
        $this->instance->setThreeDsReqPriorAuthTimestamp($value);
        return $this;
    }

    /**
     * Sets three ds req prior auth data field.
     *
     * @param string|null $value
     */
    public function threeDsReqPriorAuthData(?string $value): self
    {
        $this->instance->setThreeDsReqPriorAuthData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Three Ds Requestor Prior Authentication Info object.
     */
    public function build(): ThreeDsRequestorPriorAuthenticationInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
