<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\BroadInfo;
use FortisAPILib\Models\BrowserInformation;
use FortisAPILib\Models\Cardholder;
use FortisAPILib\Models\CardholderAccount;
use FortisAPILib\Models\ChallengeMessageExtension;
use FortisAPILib\Models\Device;
use FortisAPILib\Models\MessageExtension;
use FortisAPILib\Models\MultiTransaction;
use FortisAPILib\Models\Purchase;
use FortisAPILib\Models\ThreeDsRequestor;
use FortisAPILib\Models\V1MerchantThreedsecureAuthenticationRequest;

/**
 * Builder for model V1MerchantThreedsecureAuthenticationRequest
 *
 * @see V1MerchantThreedsecureAuthenticationRequest
 */
class V1MerchantThreedsecureAuthenticationRequestBuilder
{
    /**
     * @var V1MerchantThreedsecureAuthenticationRequest
     */
    private $instance;

    private function __construct(V1MerchantThreedsecureAuthenticationRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new V1 Merchant Threedsecure Authentication Request Builder object.
     *
     * @param string $productTransactionId
     * @param string $deviceChannel
     * @param string $messageCategory
     * @param ThreeDsRequestor $threeDsRequestor
     * @param CardholderAccount $cardholderAccount
     */
    public static function init(
        string $productTransactionId,
        string $deviceChannel,
        string $messageCategory,
        ThreeDsRequestor $threeDsRequestor,
        CardholderAccount $cardholderAccount
    ): self {
        return new self(new V1MerchantThreedsecureAuthenticationRequest(
            $productTransactionId,
            $deviceChannel,
            $messageCategory,
            $threeDsRequestor,
            $cardholderAccount
        ));
    }

    /**
     * Sets preferred protocol version field.
     *
     * @param string|null $value
     */
    public function preferredProtocolVersion(?string $value): self
    {
        $this->instance->setPreferredProtocolVersion($value);
        return $this;
    }

    /**
     * Unsets preferred protocol version field.
     */
    public function unsetPreferredProtocolVersion(): self
    {
        $this->instance->unsetPreferredProtocolVersion();
        return $this;
    }

    /**
     * Sets enforce preferred protocol version field.
     *
     * @param bool|null $value
     */
    public function enforcePreferredProtocolVersion(?bool $value): self
    {
        $this->instance->setEnforcePreferredProtocolVersion($value);
        return $this;
    }

    /**
     * Sets three ds comp ind field.
     *
     * @param string|null $value
     */
    public function threeDsCompInd(?string $value): self
    {
        $this->instance->setThreeDsCompInd($value);
        return $this;
    }

    /**
     * Unsets three ds comp ind field.
     */
    public function unsetThreeDsCompInd(): self
    {
        $this->instance->unsetThreeDsCompInd();
        return $this;
    }

    /**
     * Sets three ds method id field.
     *
     * @param string|null $value
     */
    public function threeDsMethodId(?string $value): self
    {
        $this->instance->setThreeDsMethodId($value);
        return $this;
    }

    /**
     * Unsets three ds method id field.
     */
    public function unsetThreeDsMethodId(): self
    {
        $this->instance->unsetThreeDsMethodId();
        return $this;
    }

    /**
     * Sets three ds server trans id field.
     *
     * @param string|null $value
     */
    public function threeDsServerTransId(?string $value): self
    {
        $this->instance->setThreeDsServerTransId($value);
        return $this;
    }

    /**
     * Unsets three ds server trans id field.
     */
    public function unsetThreeDsServerTransId(): self
    {
        $this->instance->unsetThreeDsServerTransId();
        return $this;
    }

    /**
     * Sets three ds requestor url field.
     *
     * @param string|null $value
     */
    public function threeDsRequestorUrl(?string $value): self
    {
        $this->instance->setThreeDsRequestorUrl($value);
        return $this;
    }

    /**
     * Unsets three ds requestor url field.
     */
    public function unsetThreeDsRequestorUrl(): self
    {
        $this->instance->unsetThreeDsRequestorUrl();
        return $this;
    }

    /**
     * Sets cardholder field.
     *
     * @param Cardholder|null $value
     */
    public function cardholder(?Cardholder $value): self
    {
        $this->instance->setCardholder($value);
        return $this;
    }

    /**
     * Sets purchase field.
     *
     * @param Purchase|null $value
     */
    public function purchase(?Purchase $value): self
    {
        $this->instance->setPurchase($value);
        return $this;
    }

    /**
     * Sets broad info field.
     *
     * @param BroadInfo|null $value
     */
    public function broadInfo(?BroadInfo $value): self
    {
        $this->instance->setBroadInfo($value);
        return $this;
    }

    /**
     * Sets message extension field.
     *
     * @param MessageExtension[]|null $value
     */
    public function messageExtension(?array $value): self
    {
        $this->instance->setMessageExtension($value);
        return $this;
    }

    /**
     * Sets challenge message extension field.
     *
     * @param ChallengeMessageExtension[]|null $value
     */
    public function challengeMessageExtension(?array $value): self
    {
        $this->instance->setChallengeMessageExtension($value);
        return $this;
    }

    /**
     * Sets browser information field.
     *
     * @param BrowserInformation|null $value
     */
    public function browserInformation(?BrowserInformation $value): self
    {
        $this->instance->setBrowserInformation($value);
        return $this;
    }

    /**
     * Sets three ri ind field.
     *
     * @param string|null $value
     */
    public function threeRiInd(?string $value): self
    {
        $this->instance->setThreeRiInd($value);
        return $this;
    }

    /**
     * Unsets three ri ind field.
     */
    public function unsetThreeRiInd(): self
    {
        $this->instance->unsetThreeRiInd();
        return $this;
    }

    /**
     * Sets device field.
     *
     * @param Device|null $value
     */
    public function device(?Device $value): self
    {
        $this->instance->setDevice($value);
        return $this;
    }

    /**
     * Sets multi transaction field.
     *
     * @param MultiTransaction|null $value
     */
    public function multiTransaction(?MultiTransaction $value): self
    {
        $this->instance->setMultiTransaction($value);
        return $this;
    }

    /**
     * Sets device id field.
     *
     * @param string|null $value
     */
    public function deviceId(?string $value): self
    {
        $this->instance->setDeviceId($value);
        return $this;
    }

    /**
     * Unsets device id field.
     */
    public function unsetDeviceId(): self
    {
        $this->instance->unsetDeviceId();
        return $this;
    }

    /**
     * Sets user id field.
     *
     * @param string|null $value
     */
    public function userId(?string $value): self
    {
        $this->instance->setUserId($value);
        return $this;
    }

    /**
     * Unsets user id field.
     */
    public function unsetUserId(): self
    {
        $this->instance->unsetUserId();
        return $this;
    }

    /**
     * Sets payee origin field.
     *
     * @param string|null $value
     */
    public function payeeOrigin(?string $value): self
    {
        $this->instance->setPayeeOrigin($value);
        return $this;
    }

    /**
     * Unsets payee origin field.
     */
    public function unsetPayeeOrigin(): self
    {
        $this->instance->unsetPayeeOrigin();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new V1 Merchant Threedsecure Authentication Request object.
     */
    public function build(): V1MerchantThreedsecureAuthenticationRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
