<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\V1PaylinksRequest;

/**
 * Builder for model V1PaylinksRequest
 *
 * @see V1PaylinksRequest
 */
class V1PaylinksRequestBuilder
{
    /**
     * @var V1PaylinksRequest
     */
    private $instance;

    private function __construct(V1PaylinksRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new V1 Paylinks Request Builder object.
     *
     * @param int $amountDue
     */
    public static function init(int $amountDue): self
    {
        return new self(new V1PaylinksRequest($amountDue));
    }

    /**
     * Sets location id field.
     *
     * @param string|null $value
     */
    public function locationId(?string $value): self
    {
        $this->instance->setLocationId($value);
        return $this;
    }

    /**
     * Unsets location id field.
     */
    public function unsetLocationId(): self
    {
        $this->instance->unsetLocationId();
        return $this;
    }

    /**
     * Sets cc product transaction id field.
     *
     * @param string|null $value
     */
    public function ccProductTransactionId(?string $value): self
    {
        $this->instance->setCcProductTransactionId($value);
        return $this;
    }

    /**
     * Unsets cc product transaction id field.
     */
    public function unsetCcProductTransactionId(): self
    {
        $this->instance->unsetCcProductTransactionId();
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Unsets email field.
     */
    public function unsetEmail(): self
    {
        $this->instance->unsetEmail();
        return $this;
    }

    /**
     * Sets location api id field.
     *
     * @param string|null $value
     */
    public function locationApiId(?string $value): self
    {
        $this->instance->setLocationApiId($value);
        return $this;
    }

    /**
     * Unsets location api id field.
     */
    public function unsetLocationApiId(): self
    {
        $this->instance->unsetLocationApiId();
        return $this;
    }

    /**
     * Sets contact id field.
     *
     * @param string|null $value
     */
    public function contactId(?string $value): self
    {
        $this->instance->setContactId($value);
        return $this;
    }

    /**
     * Unsets contact id field.
     */
    public function unsetContactId(): self
    {
        $this->instance->unsetContactId();
        return $this;
    }

    /**
     * Sets contact api id field.
     *
     * @param string|null $value
     */
    public function contactApiId(?string $value): self
    {
        $this->instance->setContactApiId($value);
        return $this;
    }

    /**
     * Unsets contact api id field.
     */
    public function unsetContactApiId(): self
    {
        $this->instance->unsetContactApiId();
        return $this;
    }

    /**
     * Sets paylink api id field.
     *
     * @param string|null $value
     */
    public function paylinkApiId(?string $value): self
    {
        $this->instance->setPaylinkApiId($value);
        return $this;
    }

    /**
     * Unsets paylink api id field.
     */
    public function unsetPaylinkApiId(): self
    {
        $this->instance->unsetPaylinkApiId();
        return $this;
    }

    /**
     * Sets ach product transaction id field.
     *
     * @param string|null $value
     */
    public function achProductTransactionId(?string $value): self
    {
        $this->instance->setAchProductTransactionId($value);
        return $this;
    }

    /**
     * Unsets ach product transaction id field.
     */
    public function unsetAchProductTransactionId(): self
    {
        $this->instance->unsetAchProductTransactionId();
        return $this;
    }

    /**
     * Sets expire date field.
     *
     * @param string|null $value
     */
    public function expireDate(?string $value): self
    {
        $this->instance->setExpireDate($value);
        return $this;
    }

    /**
     * Unsets expire date field.
     */
    public function unsetExpireDate(): self
    {
        $this->instance->unsetExpireDate();
        return $this;
    }

    /**
     * Sets display product transaction receipt details field.
     *
     * @param bool|null $value
     */
    public function displayProductTransactionReceiptDetails(?bool $value): self
    {
        $this->instance->setDisplayProductTransactionReceiptDetails($value);
        return $this;
    }

    /**
     * Sets display billing fields field.
     *
     * @param bool|null $value
     */
    public function displayBillingFields(?bool $value): self
    {
        $this->instance->setDisplayBillingFields($value);
        return $this;
    }

    /**
     * Sets delivery method field.
     *
     * @param int|null $value
     */
    public function deliveryMethod(?int $value): self
    {
        $this->instance->setDeliveryMethod($value);
        return $this;
    }

    /**
     * Unsets delivery method field.
     */
    public function unsetDeliveryMethod(): self
    {
        $this->instance->unsetDeliveryMethod();
        return $this;
    }

    /**
     * Sets cell phone field.
     *
     * @param string|null $value
     */
    public function cellPhone(?string $value): self
    {
        $this->instance->setCellPhone($value);
        return $this;
    }

    /**
     * Unsets cell phone field.
     */
    public function unsetCellPhone(): self
    {
        $this->instance->unsetCellPhone();
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets store token field.
     *
     * @param bool|null $value
     */
    public function storeToken(?bool $value): self
    {
        $this->instance->setStoreToken($value);
        return $this;
    }

    /**
     * Sets store token title field.
     *
     * @param string|null $value
     */
    public function storeTokenTitle(?string $value): self
    {
        $this->instance->setStoreTokenTitle($value);
        return $this;
    }

    /**
     * Unsets store token title field.
     */
    public function unsetStoreTokenTitle(): self
    {
        $this->instance->unsetStoreTokenTitle();
        return $this;
    }

    /**
     * Sets paylink action field.
     *
     * @param string|null $value
     */
    public function paylinkAction(?string $value): self
    {
        $this->instance->setPaylinkAction($value);
        return $this;
    }

    /**
     * Unsets paylink action field.
     */
    public function unsetPaylinkAction(): self
    {
        $this->instance->unsetPaylinkAction();
        return $this;
    }

    /**
     * Sets bank funded only override field.
     *
     * @param bool|null $value
     */
    public function bankFundedOnlyOverride(?bool $value): self
    {
        $this->instance->setBankFundedOnlyOverride($value);
        return $this;
    }

    /**
     * Sets tags field.
     *
     * @param string[]|null $value
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Unsets tags field.
     */
    public function unsetTags(): self
    {
        $this->instance->unsetTags();
        return $this;
    }

    /**
     * Sets redirect url delay field.
     *
     * @param float|null $value
     */
    public function redirectUrlDelay(?float $value): self
    {
        $this->instance->setRedirectUrlDelay($value);
        return $this;
    }

    /**
     * Unsets redirect url delay field.
     */
    public function unsetRedirectUrlDelay(): self
    {
        $this->instance->unsetRedirectUrlDelay();
        return $this;
    }

    /**
     * Sets redirect url on approve field.
     *
     * @param string|null $value
     */
    public function redirectUrlOnApprove(?string $value): self
    {
        $this->instance->setRedirectUrlOnApprove($value);
        return $this;
    }

    /**
     * Unsets redirect url on approve field.
     */
    public function unsetRedirectUrlOnApprove(): self
    {
        $this->instance->unsetRedirectUrlOnApprove();
        return $this;
    }

    /**
     * Sets redirect url on decline field.
     *
     * @param string|null $value
     */
    public function redirectUrlOnDecline(?string $value): self
    {
        $this->instance->setRedirectUrlOnDecline($value);
        return $this;
    }

    /**
     * Unsets redirect url on decline field.
     */
    public function unsetRedirectUrlOnDecline(): self
    {
        $this->instance->unsetRedirectUrlOnDecline();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new V1 Paylinks Request object.
     */
    public function build(): V1PaylinksRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
