<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\V1TransactionAchRetriesRequest;

/**
 * Builder for model V1TransactionAchRetriesRequest
 *
 * @see V1TransactionAchRetriesRequest
 */
class V1TransactionAchRetriesRequestBuilder
{
    /**
     * @var V1TransactionAchRetriesRequest
     */
    private $instance;

    private function __construct(V1TransactionAchRetriesRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new V1 Transaction Ach Retries Request Builder object.
     *
     * @param string $rejectedTransactionId
     */
    public static function init(string $rejectedTransactionId): self
    {
        return new self(new V1TransactionAchRetriesRequest($rejectedTransactionId));
    }

    /**
     * Sets return fee field.
     *
     * @param int|null $value
     */
    public function returnFee(?int $value): self
    {
        $this->instance->setReturnFee($value);
        return $this;
    }

    /**
     * Unsets return fee field.
     */
    public function unsetReturnFee(): self
    {
        $this->instance->unsetReturnFee();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new V1 Transaction Ach Retries Request object.
     */
    public function build(): V1TransactionAchRetriesRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
