<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Dimensions of the challenge window that has been displayed to the Cardholder. The ACS shall reply
 * with content that is formatted to appropriately render in this window to provide the best possible
 * user experience.
 *
 * Preconfigured sizes are width X height in pixels of the window displayed in the Cardholder browser
 * window. This is used only to prepare the CReq request and it is not part of the AReq flow. If not
 * present it will be omitted.
 *
 * However, when sending the Challenge Request, this field is required when device_channel = 02 (BRW).
 * >01 - 250 x 400
 * >
 * >02 - 390 x 400
 * >
 * >03 - 500 x 600
 * >
 * >04 - 600 x 400
 * >
 * >05 - Full screen
 * >
 */
class ChallengeWindowSizeEnum
{
    public const ENUM_01 = '01';

    public const ENUM_02 = '02';

    public const ENUM_03 = '03';

    public const ENUM_04 = '04';

    public const ENUM_05 = '05';

    private const _ALL_VALUES = [self::ENUM_01, self::ENUM_02, self::ENUM_03, self::ENUM_04, self::ENUM_05];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ChallengeWindowSizeEnum.");
    }
}
