<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use FortisAPILib\ApiHelper;
use stdClass;

class Conditions43 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $method;

    /**
     * @var string|null
     */
    private $values;

    /**
     * Returns Method.
     */
    public function getMethod(): ?string
    {
        return $this->method;
    }

    /**
     * Sets Method.
     *
     * @maps method
     * @factory \FortisAPILib\Models\Method5Enum::checkValue
     */
    public function setMethod(?string $method): void
    {
        $this->method = $method;
    }

    /**
     * Returns Values.
     */
    public function getValues(): ?string
    {
        return $this->values;
    }

    /**
     * Sets Values.
     *
     * @maps values
     * @factory \FortisAPILib\Models\Values7Enum::checkValue
     */
    public function setValues(?string $values): void
    {
        $this->values = $values;
    }

    /**
     * Converts the Conditions43 object to a human-readable string representation.
     *
     * @return string The string representation of the Conditions43 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Conditions43',
            [
                'method' => $this->method,
                'values' => $this->values,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->method)) {
            $json['method'] = Method5Enum::checkValue($this->method);
        }
        if (isset($this->values)) {
            $json['values'] = Values7Enum::checkValue($this->values);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
