<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use FortisAPILib\ApiHelper;
use stdClass;

class Data37 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $merchantSession;

    /**
     * Returns Merchant Session.
     * String formatted merchantSession object.  Needs to be passed to the session.
     * completeMerchantValidation event in JS.
     */
    public function getMerchantSession(): ?string
    {
        return $this->merchantSession;
    }

    /**
     * Sets Merchant Session.
     * String formatted merchantSession object.  Needs to be passed to the session.
     * completeMerchantValidation event in JS.
     *
     * @maps merchantSession
     */
    public function setMerchantSession(?string $merchantSession): void
    {
        $this->merchantSession = $merchantSession;
    }

    /**
     * Converts the Data37 object to a human-readable string representation.
     *
     * @return string The string representation of the Data37 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Data37',
            ['merchantSession' => $this->merchantSession, 'additionalProperties' => $this->additionalProperties]
        );
    }

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->merchantSession)) {
            $json['merchantSession'] = $this->merchantSession;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
