<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use FortisAPILib\ApiHelper;
use stdClass;

class Method50 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $type;

    /**
     * @var string
     */
    private $productTransactionId;

    /**
     * @param string $type
     * @param string $productTransactionId
     */
    public function __construct(string $type, string $productTransactionId)
    {
        $this->type = $type;
        $this->productTransactionId = $productTransactionId;
    }

    /**
     * Returns Type.
     * Payment type. Must be unique.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Payment type. Must be unique.
     *
     * @required
     * @maps type
     * @factory \FortisAPILib\Models\Type29Enum::checkValue
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Product Transaction Id.
     * The Product's method (cc/ach) has to match the type.
     */
    public function getProductTransactionId(): string
    {
        return $this->productTransactionId;
    }

    /**
     * Sets Product Transaction Id.
     * The Product's method (cc/ach) has to match the type.
     *
     * @required
     * @maps product_transaction_id
     */
    public function setProductTransactionId(string $productTransactionId): void
    {
        $this->productTransactionId = $productTransactionId;
    }

    /**
     * Converts the Method50 object to a human-readable string representation.
     *
     * @return string The string representation of the Method50 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Method50',
            [
                'type' => $this->type,
                'productTransactionId' => $this->productTransactionId,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['type']                   = Type29Enum::checkValue($this->type);
        $json['product_transaction_id'] = $this->productTransactionId;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
