<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * ID for the scheme to which the Cardholder's acctNumber belongs to. It will be used to identify the
 * Scheme from the 3DS Server configuration.
 */
class SchemeIdEnum
{
    public const VISA = 'Visa';

    public const MASTERCARD = 'Mastercard';

    public const ENUM_AMERICAN_EXPRESS = 'American Express';

    public const DINERS = 'Diners';

    private const _ALL_VALUES = [self::VISA, self::MASTERCARD, self::ENUM_AMERICAN_EXPRESS, self::DINERS];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for SchemeIdEnum.");
    }
}
